apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gcpFilestoreBackups.fullname" . }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  labels:
    {{- include "gcpFilestoreBackups.labels" . | nindent 4 }}
